CREATE TABLE IF NOT EXISTS `#__ortana_articles` (
	`id` BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`title` TEXT NOT NULL,
	`cost` INT NOT NULL,
	`description` LONGTEXT NULL,

  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
